server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    property:
      sendTopic: "order-topic"
      receiveTopic: "order-status-topic"
      groupId: "orderGroupId"
