spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    property:
      sendTopic: "order-status-topic"
      receiveTopic: "order-topic"
      groupId: "orderStatusTopicGroupId"
      statuses:
        - CREATED
        - PROCESS